#!/usr/bin/ruby
require 'rainbow/ext/string'
require_relative 'card'
require_relative 'category'
require_relative 'command'

def check_command(command)
  commands = %w(create show open delete save add remove exit instruction)
  commands.include?(command)
end

@default_category = Category.new('default.txt')
@default_category.instruction
@default_category.show_categories

commands = []

while line = $stdin.gets
  commands.push(Command.new(@default_category, line))
  commands.last.execute
end

# check rstrip +
# remove \n when read file +
# parse name of card list +
# choose active card list by name
# save card_lists by command
