#!/usr/bin/ruby
require 'rainbow/ext/string'
require_relative 'card'
require_relative 'category'
require_relative 'command'

def show_message(message)
  if block_given?
    message = yield(message)
  end
  puts message
end

# def check_command(command)
#   commands = %w(create show open delete save add remove exit instruction)
#   commands.include?(command)
# end

@category = Category.new('default.txt')
@category.instruction
@category.show_categories

commands = []

while line = $stdin.gets
  commands.push(Command.new(@category, line))
  @category = commands.last.category
end
